name: Amazon Product Analysis Test

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 0 * * *'
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Compile Project
        run: mvn clean compile

      - name: Run Tests
        run: mvn test -Dtest="testcases.**"

      - name: Generate Test Report
        run: |
          mvn surefire-report:report-only
          mvn site -DgenerateReports=false

      - name: Upload Test Report Artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: target/site